version: '3.1'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  phpMyAdmin:
    depends_on:
      - mysql
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
